[versions]
jdk = "8"
checkstyle = "8.45.1"

[plugins]

[libraries]
# lint
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
rulebook-checkstyle = "com.hendraanggrian.rulebook:rulebook-checkstyle:0.1"
# main
# test
truth = "com.google.truth:truth:1.1.3"
